$env:PORT = '3000'
$env:MONGODB_URI = 'mongodb://localhost:27017/payment_system'
$env:REDIS_URL = 'redis://localhost:6379'
$env:MAX_RETRY_ATTEMPTS = '3'
$env:RETRY_BASE_DELAY_MS = '1000'
$env:GATEWAY_TIMEOUT_MS = '5000'
$env:CIRCUIT_BREAKER_THRESHOLD = '5'
$env:CIRCUIT_BREAKER_RESET_MS = '30000'
$env:RATE_LIMIT_WINDOW_MS = '60000'
$env:RATE_LIMIT_MAX_REQUESTS = '100'
$env:NODE_ENV = 'development'

Set-Location 'D:\In\paymentGateway'
& 'C:\Users\khush\.cache\codex-runtimes\codex-primary-runtime\dependencies\node\bin\node.exe' '.\src\app.js'
